-- SQL Statements to add hebrew_nicename field and populate with Hebrew country names

-- Step 1: Add the new column to the country table
ALTER TABLE `country` ADD COLUMN `hebrew_nicename` VARCHAR(80) DEFAULT NULL AFTER `nicename`;

-- Step 2: Update all country records with Hebrew translations
UPDATE `country` SET `hebrew_nicename` = 'אפגניסטן' WHERE `country_id` = 1;
UPDATE `country` SET `hebrew_nicename` = 'אלבניה' WHERE `country_id` = 2;
UPDATE `country` SET `hebrew_nicename` = 'אלג\'יריה' WHERE `country_id` = 3;
UPDATE `country` SET `hebrew_nicename` = 'סמואה האמריקנית' WHERE `country_id` = 4;
UPDATE `country` SET `hebrew_nicename` = 'אנדורה' WHERE `country_id` = 5;
UPDATE `country` SET `hebrew_nicename` = 'אנגולה' WHERE `country_id` = 6;
UPDATE `country` SET `hebrew_nicename` = 'אנגווילה' WHERE `country_id` = 7;
UPDATE `country` SET `hebrew_nicename` = 'אנטארקטיקה' WHERE `country_id` = 8;
UPDATE `country` SET `hebrew_nicename` = 'אנטיגואה וברבודה' WHERE `country_id` = 9;
UPDATE `country` SET `hebrew_nicename` = 'ארגנטינה' WHERE `country_id` = 10;
UPDATE `country` SET `hebrew_nicename` = 'ארמניה' WHERE `country_id` = 11;
UPDATE `country` SET `hebrew_nicename` = 'ארובה' WHERE `country_id` = 12;
UPDATE `country` SET `hebrew_nicename` = 'אוסטרליה' WHERE `country_id` = 13;
UPDATE `country` SET `hebrew_nicename` = 'אוסטריה' WHERE `country_id` = 14;
UPDATE `country` SET `hebrew_nicename` = 'אזרבייג\'ן' WHERE `country_id` = 15;
UPDATE `country` SET `hebrew_nicename` = 'איי בהאמה' WHERE `country_id` = 16;
UPDATE `country` SET `hebrew_nicename` = 'בחריין' WHERE `country_id` = 17;
UPDATE `country` SET `hebrew_nicename` = 'בנגלדש' WHERE `country_id` = 18;
UPDATE `country` SET `hebrew_nicename` = 'ברבדוס' WHERE `country_id` = 19;
UPDATE `country` SET `hebrew_nicename` = 'בלארוס' WHERE `country_id` = 20;
UPDATE `country` SET `hebrew_nicename` = 'בלגיה' WHERE `country_id` = 21;
UPDATE `country` SET `hebrew_nicename` = 'בליז' WHERE `country_id` = 22;
UPDATE `country` SET `hebrew_nicename` = 'בנין' WHERE `country_id` = 23;
UPDATE `country` SET `hebrew_nicename` = 'ברמודה' WHERE `country_id` = 24;
UPDATE `country` SET `hebrew_nicename` = 'בהוטן' WHERE `country_id` = 25;
UPDATE `country` SET `hebrew_nicename` = 'בוליביה' WHERE `country_id` = 26;
UPDATE `country` SET `hebrew_nicename` = 'בוסניה והרצגובינה' WHERE `country_id` = 27;
UPDATE `country` SET `hebrew_nicename` = 'בוצואנה' WHERE `country_id` = 28;
UPDATE `country` SET `hebrew_nicename` = 'איי בובה' WHERE `country_id` = 29;
UPDATE `country` SET `hebrew_nicename` = 'ברזיל' WHERE `country_id` = 30;
UPDATE `country` SET `hebrew_nicename` = 'הטריטוריה הבריטית באוקיינוס ההודי' WHERE `country_id` = 31;
UPDATE `country` SET `hebrew_nicename` = 'ברוניי' WHERE `country_id` = 32;
UPDATE `country` SET `hebrew_nicename` = 'בולגריה' WHERE `country_id` = 33;
UPDATE `country` SET `hebrew_nicename` = 'בורקינה פאסו' WHERE `country_id` = 34;
UPDATE `country` SET `hebrew_nicename` = 'בורונדי' WHERE `country_id` = 35;
UPDATE `country` SET `hebrew_nicename` = 'קמבודיה' WHERE `country_id` = 36;
UPDATE `country` SET `hebrew_nicename` = 'קמרון' WHERE `country_id` = 37;
UPDATE `country` SET `hebrew_nicename` = 'קנדה' WHERE `country_id` = 38;
UPDATE `country` SET `hebrew_nicename` = 'כף ורדה' WHERE `country_id` = 39;
UPDATE `country` SET `hebrew_nicename` = 'איי קיימן' WHERE `country_id` = 40;
UPDATE `country` SET `hebrew_nicename` = 'הרפובליקה המרכז-אפריקאית' WHERE `country_id` = 41;
UPDATE `country` SET `hebrew_nicename` = 'צ\'אד' WHERE `country_id` = 42;
UPDATE `country` SET `hebrew_nicename` = 'צ\'ילה' WHERE `country_id` = 43;
UPDATE `country` SET `hebrew_nicename` = 'סין' WHERE `country_id` = 44;
UPDATE `country` SET `hebrew_nicename` = 'אי חג המולד' WHERE `country_id` = 45;
UPDATE `country` SET `hebrew_nicename` = 'איי קוקוס' WHERE `country_id` = 46;
UPDATE `country` SET `hebrew_nicename` = 'קולומביה' WHERE `country_id` = 47;
UPDATE `country` SET `hebrew_nicename` = 'קומורו' WHERE `country_id` = 48;
UPDATE `country` SET `hebrew_nicename` = 'קונגו' WHERE `country_id` = 49;
UPDATE `country` SET `hebrew_nicename` = 'הרפובליקה הדמוקרטית של קונגו' WHERE `country_id` = 50;
UPDATE `country` SET `hebrew_nicename` = 'איי קוק' WHERE `country_id` = 51;
UPDATE `country` SET `hebrew_nicename` = 'קוסטה ריקה' WHERE `country_id` = 52;
UPDATE `country` SET `hebrew_nicename` = 'חוף השנהב' WHERE `country_id` = 53;
UPDATE `country` SET `hebrew_nicename` = 'קרואטיה' WHERE `country_id` = 54;
UPDATE `country` SET `hebrew_nicename` = 'קובה' WHERE `country_id` = 55;
UPDATE `country` SET `hebrew_nicename` = 'קפריסין' WHERE `country_id` = 56;
UPDATE `country` SET `hebrew_nicename` = 'הרפובליקה הצ\'כית' WHERE `country_id` = 57;
UPDATE `country` SET `hebrew_nicename` = 'דנמרק' WHERE `country_id` = 58;
UPDATE `country` SET `hebrew_nicename` = 'ג\'יבוטי' WHERE `country_id` = 59;
UPDATE `country` SET `hebrew_nicename` = 'דומיניקה' WHERE `country_id` = 60;
UPDATE `country` SET `hebrew_nicename` = 'הרפובליקה הדומיניקנית' WHERE `country_id` = 61;
UPDATE `country` SET `hebrew_nicename` = 'אקוודור' WHERE `country_id` = 62;
UPDATE `country` SET `hebrew_nicename` = 'מצרים' WHERE `country_id` = 63;
UPDATE `country` SET `hebrew_nicename` = 'אל סלבדור' WHERE `country_id` = 64;
UPDATE `country` SET `hebrew_nicename` = 'גינאה המשוונית' WHERE `country_id` = 65;
UPDATE `country` SET `hebrew_nicename` = 'אריתריאה' WHERE `country_id` = 66;
UPDATE `country` SET `hebrew_nicename` = 'אסטוניה' WHERE `country_id` = 67;
UPDATE `country` SET `hebrew_nicename` = 'אתיופיה' WHERE `country_id` = 68;
UPDATE `country` SET `hebrew_nicename` = 'איי פוקלנד' WHERE `country_id` = 69;
UPDATE `country` SET `hebrew_nicename` = 'איי פארו' WHERE `country_id` = 70;
UPDATE `country` SET `hebrew_nicename` = 'פיג\'י' WHERE `country_id` = 71;
UPDATE `country` SET `hebrew_nicename` = 'פינלנד' WHERE `country_id` = 72;
UPDATE `country` SET `hebrew_nicename` = 'צרפת' WHERE `country_id` = 73;
UPDATE `country` SET `hebrew_nicename` = 'גיאנה הצרפתית' WHERE `country_id` = 74;
UPDATE `country` SET `hebrew_nicename` = 'פולינזיה הצרפתית' WHERE `country_id` = 75;
UPDATE `country` SET `hebrew_nicename` = 'הטריטוריות הדרומיות של צרפת' WHERE `country_id` = 76;
UPDATE `country` SET `hebrew_nicename` = 'גבון' WHERE `country_id` = 77;
UPDATE `country` SET `hebrew_nicename` = 'גמביה' WHERE `country_id` = 78;
UPDATE `country` SET `hebrew_nicename` = 'גאורגיה' WHERE `country_id` = 79;
UPDATE `country` SET `hebrew_nicename` = 'גרמניה' WHERE `country_id` = 80;
UPDATE `country` SET `hebrew_nicename` = 'גאנה' WHERE `country_id` = 81;
UPDATE `country` SET `hebrew_nicename` = 'גיברלטר' WHERE `country_id` = 82;
UPDATE `country` SET `hebrew_nicename` = 'יוון' WHERE `country_id` = 83;
UPDATE `country` SET `hebrew_nicename` = 'גרינלנד' WHERE `country_id` = 84;
UPDATE `country` SET `hebrew_nicename` = 'גרנדה' WHERE `country_id` = 85;
UPDATE `country` SET `hebrew_nicename` = 'גוואדלופ' WHERE `country_id` = 86;
UPDATE `country` SET `hebrew_nicename` = 'גואם' WHERE `country_id` = 87;
UPDATE `country` SET `hebrew_nicename` = 'גואטמלה' WHERE `country_id` = 88;
UPDATE `country` SET `hebrew_nicename` = 'גינאה' WHERE `country_id` = 89;
UPDATE `country` SET `hebrew_nicename` = 'גינאה-ביסאו' WHERE `country_id` = 90;
UPDATE `country` SET `hebrew_nicename` = 'גיאנה' WHERE `country_id` = 91;
UPDATE `country` SET `hebrew_nicename` = 'האיטי' WHERE `country_id` = 92;
UPDATE `country` SET `hebrew_nicename` = 'איי הרד ומקדונלד' WHERE `country_id` = 93;
UPDATE `country` SET `hebrew_nicename` = 'הכס הקדוש (קריית הוותיקן)' WHERE `country_id` = 94;
UPDATE `country` SET `hebrew_nicename` = 'הונדורס' WHERE `country_id` = 95;
UPDATE `country` SET `hebrew_nicename` = 'הונג קונג' WHERE `country_id` = 96;
UPDATE `country` SET `hebrew_nicename` = 'הונגריה' WHERE `country_id` = 97;
UPDATE `country` SET `hebrew_nicename` = 'איסלנד' WHERE `country_id` = 98;
UPDATE `country` SET `hebrew_nicename` = 'הודו' WHERE `country_id` = 99;
UPDATE `country` SET `hebrew_nicename` = 'אינדונזיה' WHERE `country_id` = 100;
UPDATE `country` SET `hebrew_nicename` = 'איראן' WHERE `country_id` = 101;
UPDATE `country` SET `hebrew_nicename` = 'עיראק' WHERE `country_id` = 102;
UPDATE `country` SET `hebrew_nicename` = 'אירלנד' WHERE `country_id` = 103;
UPDATE `country` SET `hebrew_nicename` = 'ישראל' WHERE `country_id` = 104;
UPDATE `country` SET `hebrew_nicename` = 'איטליה' WHERE `country_id` = 105;
UPDATE `country` SET `hebrew_nicename` = 'ג\'מייקה' WHERE `country_id` = 106;
UPDATE `country` SET `hebrew_nicename` = 'יפן' WHERE `country_id` = 107;
UPDATE `country` SET `hebrew_nicename` = 'ירדן' WHERE `country_id` = 108;
UPDATE `country` SET `hebrew_nicename` = 'קזחסטן' WHERE `country_id` = 109;
UPDATE `country` SET `hebrew_nicename` = 'קניה' WHERE `country_id` = 110;
UPDATE `country` SET `hebrew_nicename` = 'קיריבטי' WHERE `country_id` = 111;
UPDATE `country` SET `hebrew_nicename` = 'קוריאה הצפונית' WHERE `country_id` = 112;
UPDATE `country` SET `hebrew_nicename` = 'קוריאה הדרומית' WHERE `country_id` = 113;
UPDATE `country` SET `hebrew_nicename` = 'כווית' WHERE `country_id` = 114;
UPDATE `country` SET `hebrew_nicename` = 'קירגיזסטן' WHERE `country_id` = 115;
UPDATE `country` SET `hebrew_nicename` = 'לאוס' WHERE `country_id` = 116;
UPDATE `country` SET `hebrew_nicename` = 'לטביה' WHERE `country_id` = 117;
UPDATE `country` SET `hebrew_nicename` = 'לבנון' WHERE `country_id` = 118;
UPDATE `country` SET `hebrew_nicename` = 'לסוטו' WHERE `country_id` = 119;
UPDATE `country` SET `hebrew_nicename` = 'ליבריה' WHERE `country_id` = 120;
UPDATE `country` SET `hebrew_nicename` = 'לוב' WHERE `country_id` = 121;
UPDATE `country` SET `hebrew_nicename` = 'ליכטנשטיין' WHERE `country_id` = 122;
UPDATE `country` SET `hebrew_nicename` = 'ליטא' WHERE `country_id` = 123;
UPDATE `country` SET `hebrew_nicename` = 'לוקסמבורג' WHERE `country_id` = 124;
UPDATE `country` SET `hebrew_nicename` = 'מקאו' WHERE `country_id` = 125;
UPDATE `country` SET `hebrew_nicename` = 'מקדוניה' WHERE `country_id` = 126;
UPDATE `country` SET `hebrew_nicename` = 'מדגסקר' WHERE `country_id` = 127;
UPDATE `country` SET `hebrew_nicename` = 'מלאווי' WHERE `country_id` = 128;
UPDATE `country` SET `hebrew_nicename` = 'מלזיה' WHERE `country_id` = 129;
UPDATE `country` SET `hebrew_nicename` = 'האיים המלדיביים' WHERE `country_id` = 130;
UPDATE `country` SET `hebrew_nicename` = 'מאלי' WHERE `country_id` = 131;
UPDATE `country` SET `hebrew_nicename` = 'מלטה' WHERE `country_id` = 132;
UPDATE `country` SET `hebrew_nicename` = 'איי מרשל' WHERE `country_id` = 133;
UPDATE `country` SET `hebrew_nicename` = 'מרטיניק' WHERE `country_id` = 134;
UPDATE `country` SET `hebrew_nicename` = 'מאוריטניה' WHERE `country_id` = 135;
UPDATE `country` SET `hebrew_nicename` = 'מאוריציוס' WHERE `country_id` = 136;
UPDATE `country` SET `hebrew_nicename` = 'מיוט' WHERE `country_id` = 137;
UPDATE `country` SET `hebrew_nicename` = 'מקסיקו' WHERE `country_id` = 138;
UPDATE `country` SET `hebrew_nicename` = 'מיקרונזיה' WHERE `country_id` = 139;
UPDATE `country` SET `hebrew_nicename` = 'מולדובה' WHERE `country_id` = 140;
UPDATE `country` SET `hebrew_nicename` = 'מונקו' WHERE `country_id` = 141;
UPDATE `country` SET `hebrew_nicename` = 'מונגוליה' WHERE `country_id` = 142;
UPDATE `country` SET `hebrew_nicename` = 'מונסראט' WHERE `country_id` = 143;
UPDATE `country` SET `hebrew_nicename` = 'מרוקו' WHERE `country_id` = 144;
UPDATE `country` SET `hebrew_nicename` = 'מוזמביק' WHERE `country_id` = 145;
UPDATE `country` SET `hebrew_nicename` = 'מיאנמר' WHERE `country_id` = 146;
UPDATE `country` SET `hebrew_nicename` = 'נמיביה' WHERE `country_id` = 147;
UPDATE `country` SET `hebrew_nicename` = 'נאורו' WHERE `country_id` = 148;
UPDATE `country` SET `hebrew_nicename` = 'נפאל' WHERE `country_id` = 149;
UPDATE `country` SET `hebrew_nicename` = 'הולנד' WHERE `country_id` = 150;
UPDATE `country` SET `hebrew_nicename` = 'האנטילים ההולנדיים' WHERE `country_id` = 151;
UPDATE `country` SET `hebrew_nicename` = 'קלדוניה החדשה' WHERE `country_id` = 152;
UPDATE `country` SET `hebrew_nicename` = 'ניו זילנד' WHERE `country_id` = 153;
UPDATE `country` SET `hebrew_nicename` = 'ניקרגואה' WHERE `country_id` = 154;
UPDATE `country` SET `hebrew_nicename` = 'ניז\'ר' WHERE `country_id` = 155;
UPDATE `country` SET `hebrew_nicename` = 'ניגריה' WHERE `country_id` = 156;
UPDATE `country` SET `hebrew_nicename` = 'ניווה' WHERE `country_id` = 157;
UPDATE `country` SET `hebrew_nicename` = 'איי נורפוק' WHERE `country_id` = 158;
UPDATE `country` SET `hebrew_nicename` = 'איי מריאנה הצפוניים' WHERE `country_id` = 159;
UPDATE `country` SET `hebrew_nicename` = 'נורווגיה' WHERE `country_id` = 160;
UPDATE `country` SET `hebrew_nicename` = 'עומאן' WHERE `country_id` = 161;
UPDATE `country` SET `hebrew_nicename` = 'פקיסטן' WHERE `country_id` = 162;
UPDATE `country` SET `hebrew_nicename` = 'פלאו' WHERE `country_id` = 163;
UPDATE `country` SET `hebrew_nicename` = 'השטחים הפלסטיניים' WHERE `country_id` = 164;
UPDATE `country` SET `hebrew_nicename` = 'פנמה' WHERE `country_id` = 165;
UPDATE `country` SET `hebrew_nicename` = 'פפואה גינאה החדשה' WHERE `country_id` = 166;
UPDATE `country` SET `hebrew_nicename` = 'פרגוואי' WHERE `country_id` = 167;
UPDATE `country` SET `hebrew_nicename` = 'פרו' WHERE `country_id` = 168;
UPDATE `country` SET `hebrew_nicename` = 'הפיליפינים' WHERE `country_id` = 169;
UPDATE `country` SET `hebrew_nicename` = 'פיטקרן' WHERE `country_id` = 170;
UPDATE `country` SET `hebrew_nicename` = 'פולין' WHERE `country_id` = 171;
UPDATE `country` SET `hebrew_nicename` = 'פורטוגל' WHERE `country_id` = 172;
UPDATE `country` SET `hebrew_nicename` = 'פוארטו ריקו' WHERE `country_id` = 173;
UPDATE `country` SET `hebrew_nicename` = 'קטאר' WHERE `country_id` = 174;
UPDATE `country` SET `hebrew_nicename` = 'ראוניון' WHERE `country_id` = 175;
UPDATE `country` SET `hebrew_nicename` = 'רומניה' WHERE `country_id` = 176;
UPDATE `country` SET `hebrew_nicename` = 'רוסיה' WHERE `country_id` = 177;
UPDATE `country` SET `hebrew_nicename` = 'רואנדה' WHERE `country_id` = 178;
UPDATE `country` SET `hebrew_nicename` = 'סנט הלנה' WHERE `country_id` = 179;
UPDATE `country` SET `hebrew_nicename` = 'סנט קיטס ונוויס' WHERE `country_id` = 180;
UPDATE `country` SET `hebrew_nicename` = 'סנט לוסיה' WHERE `country_id` = 181;
UPDATE `country` SET `hebrew_nicename` = 'סנט פייר ומיקלון' WHERE `country_id` = 182;
UPDATE `country` SET `hebrew_nicename` = 'סנט וינסנט והגרנדינים' WHERE `country_id` = 183;
UPDATE `country` SET `hebrew_nicename` = 'סמואה' WHERE `country_id` = 184;
UPDATE `country` SET `hebrew_nicename` = 'סן מרינו' WHERE `country_id` = 185;
UPDATE `country` SET `hebrew_nicename` = 'סאו טומה ופרינסיפה' WHERE `country_id` = 186;
UPDATE `country` SET `hebrew_nicename` = 'ערב הסעודית' WHERE `country_id` = 187;
UPDATE `country` SET `hebrew_nicename` = 'סנגל' WHERE `country_id` = 188;
UPDATE `country` SET `hebrew_nicename` = 'סרביה ומונטנגרו' WHERE `country_id` = 189;
UPDATE `country` SET `hebrew_nicename` = 'איי סיישל' WHERE `country_id` = 190;
UPDATE `country` SET `hebrew_nicename` = 'סיירה לאונה' WHERE `country_id` = 191;
UPDATE `country` SET `hebrew_nicename` = 'סינגפור' WHERE `country_id` = 192;
UPDATE `country` SET `hebrew_nicename` = 'סלובקיה' WHERE `country_id` = 193;
UPDATE `country` SET `hebrew_nicename` = 'סלובניה' WHERE `country_id` = 194;
UPDATE `country` SET `hebrew_nicename` = 'איי שלמה' WHERE `country_id` = 195;
UPDATE `country` SET `hebrew_nicename` = 'סומליה' WHERE `country_id` = 196;
UPDATE `country` SET `hebrew_nicename` = 'דרום אפריקה' WHERE `country_id` = 197;
UPDATE `country` SET `hebrew_nicename` = 'ג\'ורג\'יה הדרומית ואיי סנדוויץ\' הדרומיים' WHERE `country_id` = 198;
UPDATE `country` SET `hebrew_nicename` = 'ספרד' WHERE `country_id` = 199;
UPDATE `country` SET `hebrew_nicename` = 'סרי לנקה' WHERE `country_id` = 200;
UPDATE `country` SET `hebrew_nicename` = 'סודן' WHERE `country_id` = 201;
UPDATE `country` SET `hebrew_nicename` = 'סורינאם' WHERE `country_id` = 202;
UPDATE `country` SET `hebrew_nicename` = 'סבאלברד ויאן מאיין' WHERE `country_id` = 203;
UPDATE `country` SET `hebrew_nicename` = 'סווזילנד' WHERE `country_id` = 204;
UPDATE `country` SET `hebrew_nicename` = 'שוודיה' WHERE `country_id` = 205;
UPDATE `country` SET `hebrew_nicename` = 'שווייץ' WHERE `country_id` = 206;
UPDATE `country` SET `hebrew_nicename` = 'סוריה' WHERE `country_id` = 207;
UPDATE `country` SET `hebrew_nicename` = 'טייוואן' WHERE `country_id` = 208;
UPDATE `country` SET `hebrew_nicename` = 'טג\'יקיסטן' WHERE `country_id` = 209;
UPDATE `country` SET `hebrew_nicename` = 'טנזניה' WHERE `country_id` = 210;
UPDATE `country` SET `hebrew_nicename` = 'תאילנד' WHERE `country_id` = 211;
UPDATE `country` SET `hebrew_nicename` = 'טימור-לסטה' WHERE `country_id` = 212;
UPDATE `country` SET `hebrew_nicename` = 'טוגו' WHERE `country_id` = 213;
UPDATE `country` SET `hebrew_nicename` = 'טוקלאו' WHERE `country_id` = 214;
UPDATE `country` SET `hebrew_nicename` = 'טונגה' WHERE `country_id` = 215;
UPDATE `country` SET `hebrew_nicename` = 'טרינידד וטובגו' WHERE `country_id` = 216;
UPDATE `country` SET `hebrew_nicename` = 'תוניסיה' WHERE `country_id` = 217;
UPDATE `country` SET `hebrew_nicename` = 'טורקיה' WHERE `country_id` = 218;
UPDATE `country` SET `hebrew_nicename` = 'טורקמניסטן' WHERE `country_id` = 219;
UPDATE `country` SET `hebrew_nicename` = 'איי טרקס וקאיקוס' WHERE `country_id` = 220;
UPDATE `country` SET `hebrew_nicename` = 'טובאלו' WHERE `country_id` = 221;
UPDATE `country` SET `hebrew_nicename` = 'אוגנדה' WHERE `country_id` = 222;
UPDATE `country` SET `hebrew_nicename` = 'אוקראינה' WHERE `country_id` = 223;
UPDATE `country` SET `hebrew_nicename` = 'איחוד האמירויות הערביות' WHERE `country_id` = 224;
UPDATE `country` SET `hebrew_nicename` = 'הממלכה המאוחדת' WHERE `country_id` = 225;
UPDATE `country` SET `hebrew_nicename` = 'ארצות הברית' WHERE `country_id` = 226;
UPDATE `country` SET `hebrew_nicename` = 'איים קטנים של ארה"ב' WHERE `country_id` = 227;
UPDATE `country` SET `hebrew_nicename` = 'אורוגוואי' WHERE `country_id` = 228;
UPDATE `country` SET `hebrew_nicename` = 'אוזבקיסטן' WHERE `country_id` = 229;
UPDATE `country` SET `hebrew_nicename` = 'ונואטו' WHERE `country_id` = 230;
UPDATE `country` SET `hebrew_nicename` = 'ונצואלה' WHERE `country_id` = 231;
UPDATE `country` SET `hebrew_nicename` = 'וייטנאם' WHERE `country_id` = 232;
UPDATE `country` SET `hebrew_nicename` = 'איי הבתולה הבריטיים' WHERE `country_id` = 233;
UPDATE `country` SET `hebrew_nicename` = 'איי הבתולה האמריקאיים' WHERE `country_id` = 234;
UPDATE `country` SET `hebrew_nicename` = 'ווליס ופוטונה' WHERE `country_id` = 235;
UPDATE `country` SET `hebrew_nicename` = 'סהרה המערבית' WHERE `country_id` = 236;
UPDATE `country` SET `hebrew_nicename` = 'תימן' WHERE `country_id` = 237;
UPDATE `country` SET `hebrew_nicename` = 'זמביה' WHERE `country_id` = 238;
UPDATE `country` SET `hebrew_nicename` = 'זימבבואה' WHERE `country_id` = 239;
