UPDATE `pages` SET `page_for` = 'דף הבית', `name` = 'בית', `page_title` = 'דף הבית' WHERE `page_id` = 1;
UPDATE `pages` SET `page_for` = 'דף הבית', `name` = 'באנר ראשי', `page_title` = 'סליידר ראשי' WHERE `page_id` = 2;
UPDATE `pages` SET `page_for` = 'דף הבית', `name` = 'דף הבית - רוצים להדריך איתנו?', `page_title` = 'רוצים להדריך איתנו?' WHERE `page_id` = 3;
UPDATE `pages` SET `page_for` = 'דף הבית', `name` = 'דף הבית - חדש באתר', `page_title` = 'חדש באתר' WHERE `page_id` = 4;
UPDATE `pages` SET `page_for` = 'חוגים', `name` = 'חוג ראשי', `page_title` = 'באנר חוגים' WHERE `page_id` = 5;
UPDATE `pages` SET `page_for` = 'חוגים', `name` = 'תוכן חוגים', `page_title` = 'רשימת חוגים' WHERE `page_id` = 6;
UPDATE `pages` SET `page_for` = 'סיטונאות', `name` = 'סיטונאות ראשי', `page_title` = 'באנר סיטונאות' WHERE `page_id` = 7;
UPDATE `pages` SET `page_for` = 'סיטונאות', `name` = 'תוכן סיטונאות', `page_title` = 'רשימת סיטונאות' WHERE `page_id` = 8;
UPDATE `pages` SET `page_for` = 'ציורים', `name` = 'ציורים ראשי', `page_title` = 'באנר ציורים' WHERE `page_id` = 9;
UPDATE `pages` SET `page_for` = 'ציורים', `name` = 'תוכן ציורים', `page_title` = 'רשימת ציורים' WHERE `page_id` = 10;
UPDATE `pages` SET `page_for` = 'צור קשר', `name` = 'צור קשר ראשי', `page_title` = 'באנר צור קשר' WHERE `page_id` = 11;
UPDATE `pages` SET `page_for` = 'צור קשר', `name` = 'צור קשר - אימייל', `page_title` = 'אימייל' WHERE `page_id` = 12;
UPDATE `pages` SET `page_for` = 'צור קשר', `name` = 'צור קשר - ווטסאפ', `page_title` = 'ווטסאפ' WHERE `page_id` = 13;
UPDATE `pages` SET `page_for` = 'צור קשר', `name` = 'צור קשר - טלפון', `page_title` = 'טלפון' WHERE `page_id` = 14;
UPDATE `pages` SET `page_for` = 'צור קשר', `name` = 'צור קשר - כתובת', `page_title` = 'כתובת' WHERE `page_id` = 15;
UPDATE `pages` SET `page_for` = 'דפים אחרים', `name` = 'עגלת קניות ראשי', `page_title` = 'באנר עגלת קניות' WHERE `page_id` = 16;
UPDATE `pages` SET `page_for` = 'דפים אחרים', `name` = 'החשבון שלי ראשי', `page_title` = 'באנר החשבון שלי' WHERE `page_id` = 17;
UPDATE `pages` SET `page_for` = 'דפים אחרים', `name` = 'הרשמת סטודנטים ראשי', `page_title` = 'באנר הרשמת סטודנטים' WHERE `page_id` = 18;
UPDATE `pages` SET `page_for` = 'דפים אחרים', `name` = 'הזמנות ראשי', `page_title` = 'באנר הזמנות' WHERE `page_id` = 19;
UPDATE `pages` SET `page_for` = 'דפים אחרים', `name` = 'הורדות ראשי', `page_title` = 'באנר הורדות' WHERE `page_id` = 20;
UPDATE `pages` SET `page_for` = 'דפים אחרים', `name` = 'כתובת ראשי', `page_title` = 'באנר כתובת' WHERE `page_id` = 21;
UPDATE `pages` SET `page_for` = 'דפים אחרים', `name` = 'עריכת חשבון ראשי', `page_title` = 'באנר עריכת חשבון' WHERE `page_id` = 22;
UPDATE `pages` SET `page_for` = 'דפים אחרים', `name` = 'שאלון (מייק-קיט) ראשי', `page_title` = 'באנר שאלון (מייק-קיט)' WHERE `page_id` = 23;
UPDATE `pages` SET `page_for` = 'דפים אחרים', `name` = 'תשלום ראשי', `page_title` = 'באנר תשלום' WHERE `page_id` = 24;
UPDATE `pages` SET `page_for` = 'דפים אחרים', `name` = 'שאלון (מדליאן) ראשי', `page_title` = 'באנר שאלון (מדליאן)' WHERE `page_id` = 25;
UPDATE `pages` SET `page_for` = 'דפים אחרים', `name` = 'איפוס סיסמה ראשי', `page_title` = 'באנר איפוס סיסמה' WHERE `page_id` = 26;
