-- SQL UPDATE Statements to translate all descriptions in system_options table to Hebrew

UPDATE `system_options` SET `description` = 'לוח בקרה' WHERE `optid` = 1;
UPDATE `system_options` SET `description` = 'הזמנות' WHERE `optid` = 2;
UPDATE `system_options` SET `description` = 'מוצרים' WHERE `optid` = 3;
UPDATE `system_options` SET `description` = 'הוסף מוצרים' WHERE `optid` = 4;
UPDATE `system_options` SET `description` = 'כתובת SEO גלויה' WHERE `optid` = 5;
UPDATE `system_options` SET `description` = 'כל המאפיינים גלויים' WHERE `optid` = 6;
UPDATE `system_options` SET `description` = 'פרטי SEO גלויים' WHERE `optid` = 7;
UPDATE `system_options` SET `description` = 'מוצר שנוסף גלוי' WHERE `optid` = 8;
UPDATE `system_options` SET `description` = 'הצג מוצרים' WHERE `optid` = 9;
UPDATE `system_options` SET `description` = 'כל מוצרי המשתמש גלויים' WHERE `optid` = 10;
UPDATE `system_options` SET `description` = 'ערוך מוצר' WHERE `optid` = 11;
UPDATE `system_options` SET `description` = 'מחק מוצר' WHERE `optid` = 12;
UPDATE `system_options` SET `description` = 'על סטטוס מוצר' WHERE `optid` = 13;
UPDATE `system_options` SET `description` = 'אבטחה ובקרת גישה' WHERE `optid` = 14;
UPDATE `system_options` SET `description` = 'ניהול משתמשים' WHERE `optid` = 15;
UPDATE `system_options` SET `description` = 'קבוצות גישה' WHERE `optid` = 16;
UPDATE `system_options` SET `description` = 'הרשאות גישה' WHERE `optid` = 17;
UPDATE `system_options` SET `description` = 'הוסף משתמש' WHERE `optid` = 18;
UPDATE `system_options` SET `description` = 'שינוי סטטוס משתמש' WHERE `optid` = 19;
UPDATE `system_options` SET `description` = 'ערוך משתמש' WHERE `optid` = 20;
UPDATE `system_options` SET `description` = 'מחק משתמש' WHERE `optid` = 21;
UPDATE `system_options` SET `description` = 'הגדרות מסחר אלקטרוני' WHERE `optid` = 22;
UPDATE `system_options` SET `description` = 'נהל קטגוריות' WHERE `optid` = 23;
UPDATE `system_options` SET `description` = 'הוסף קטגוריה' WHERE `optid` = 24;
UPDATE `system_options` SET `description` = 'ערוך קטגוריה' WHERE `optid` = 25;
UPDATE `system_options` SET `description` = 'מחק קטגוריה' WHERE `optid` = 26;
UPDATE `system_options` SET `description` = 'שנה סטטוס קטגוריה' WHERE `optid` = 27;
UPDATE `system_options` SET `description` = 'הוסף תמונה' WHERE `optid` = 28;
UPDATE `system_options` SET `description` = 'נהל מאפיינים' WHERE `optid` = 29;
UPDATE `system_options` SET `description` = 'הוסף מאפיין' WHERE `optid` = 30;
UPDATE `system_options` SET `description` = 'ערוך מאפיין' WHERE `optid` = 31;
UPDATE `system_options` SET `description` = 'מחק מאפיין' WHERE `optid` = 32;
UPDATE `system_options` SET `description` = 'נהל ערכים' WHERE `optid` = 33;
UPDATE `system_options` SET `description` = 'הוסף ערכי מאפיין' WHERE `optid` = 34;
UPDATE `system_options` SET `description` = 'ערוך ערכי מאפיין' WHERE `optid` = 35;
UPDATE `system_options` SET `description` = 'מחק ערכי מאפיין' WHERE `optid` = 36;
UPDATE `system_options` SET `description` = 'שנה סטטוס ערך' WHERE `optid` = 37;
UPDATE `system_options` SET `description` = 'נהל מאפיינים' WHERE `optid` = 38;
UPDATE `system_options` SET `description` = 'הקצה מאפיינים' WHERE `optid` = 39;
UPDATE `system_options` SET `description` = 'הסר מאפיינים מוקצים' WHERE `optid` = 40;
UPDATE `system_options` SET `description` = 'נהל מותגים' WHERE `optid` = 41;
UPDATE `system_options` SET `description` = 'הוסף מותגים' WHERE `optid` = 42;
UPDATE `system_options` SET `description` = 'ערוך מותגים' WHERE `optid` = 43;
UPDATE `system_options` SET `description` = 'מחק מותגים' WHERE `optid` = 44;
UPDATE `system_options` SET `description` = 'נהל מותגים' WHERE `optid` = 45;
UPDATE `system_options` SET `description` = 'הקצה מותגים' WHERE `optid` = 46;
UPDATE `system_options` SET `description` = 'הסר מותגים מוקצים' WHERE `optid` = 47;
UPDATE `system_options` SET `description` = 'ערוך מוצרי משנה' WHERE `optid` = 48;
UPDATE `system_options` SET `description` = 'תעריפי משלוח' WHERE `optid` = 49;
UPDATE `system_options` SET `description` = 'הוסף תעריפי משלוח' WHERE `optid` = 50;
UPDATE `system_options` SET `description` = 'ערוך תעריפי משלוח' WHERE `optid` = 51;
UPDATE `system_options` SET `description` = 'מחק תעריפי משלוח' WHERE `optid` = 52;
UPDATE `system_options` SET `description` = 'נהל דפים' WHERE `optid` = 53;
UPDATE `system_options` SET `description` = 'הוסף דפים' WHERE `optid` = 54;
UPDATE `system_options` SET `description` = 'ערוך דפים' WHERE `optid` = 55;
UPDATE `system_options` SET `description` = 'הוסף תמונות' WHERE `optid` = 56;
UPDATE `system_options` SET `description` = 'כל ההזמנות גלויות' WHERE `optid` = 57;
UPDATE `system_options` SET `description` = 'ערוך כתובת' WHERE `optid` = 58;
UPDATE `system_options` SET `description` = 'ערוך הזמנה' WHERE `optid` = 59;
UPDATE `system_options` SET `description` = 'מחק הזמנה' WHERE `optid` = 60;
UPDATE `system_options` SET `description` = 'עדכן פרטי תשלום' WHERE `optid` = 61;
UPDATE `system_options` SET `description` = 'עדכן דמי משלוח בעת שינוי כתובת' WHERE `optid` = 62;
UPDATE `system_options` SET `description` = 'הצג הזמנות' WHERE `optid` = 63;
UPDATE `system_options` SET `description` = 'עדכן סטטוס הזמנה' WHERE `optid` = 64;
UPDATE `system_options` SET `description` = 'הצג לקוח' WHERE `optid` = 65;
UPDATE `system_options` SET `description` = 'הצג הזמנה בודדת' WHERE `optid` = 66;
UPDATE `system_options` SET `description` = 'הקצה מוצר' WHERE `optid` = 67;
UPDATE `system_options` SET `description` = 'ערוך סטטוס תשלום' WHERE `optid` = 68;
UPDATE `system_options` SET `description` = 'הוסף קטגוריות אחרות' WHERE `optid` = 69;
UPDATE `system_options` SET `description` = 'עדכן דמי משלוח' WHERE `optid` = 70;
UPDATE `system_options` SET `description` = 'עדכן הנחה' WHERE `optid` = 71;
UPDATE `system_options` SET `description` = 'עדכן סכום ששולם' WHERE `optid` = 72;
UPDATE `system_options` SET `description` = 'הצג פרטי מקבל' WHERE `optid` = 73;
UPDATE `system_options` SET `description` = 'נהל לקוחות' WHERE `optid` = 74;
UPDATE `system_options` SET `description` = 'הוסף לקוח' WHERE `optid` = 75;
UPDATE `system_options` SET `description` = 'שנה סטטוס לקוח' WHERE `optid` = 76;
UPDATE `system_options` SET `description` = 'ערוך לקוח' WHERE `optid` = 77;
UPDATE `system_options` SET `description` = 'מחק לקוח' WHERE `optid` = 78;
UPDATE `system_options` SET `description` = 'אפשרויות אחרות' WHERE `optid` = 79;
UPDATE `system_options` SET `description` = 'שער מטבע' WHERE `optid` = 80;
UPDATE `system_options` SET `description` = 'הוסף תעריפים' WHERE `optid` = 81;
UPDATE `system_options` SET `description` = 'ערוך תעריפים' WHERE `optid` = 82;
UPDATE `system_options` SET `description` = 'מחק תעריפים' WHERE `optid` = 83;
UPDATE `system_options` SET `description` = 'שנה סטטוס תעריף' WHERE `optid` = 84;
UPDATE `system_options` SET `description` = 'נהל סוג תעריף' WHERE `optid` = 85;
UPDATE `system_options` SET `description` = 'קופונים' WHERE `optid` = 86;
UPDATE `system_options` SET `description` = 'הוסף קופונים' WHERE `optid` = 87;
UPDATE `system_options` SET `description` = 'ערוך קופונים' WHERE `optid` = 88;
UPDATE `system_options` SET `description` = 'מחק קופונים' WHERE `optid` = 89;
UPDATE `system_options` SET `description` = 'שנה סטטוס קופונים' WHERE `optid` = 90;
UPDATE `system_options` SET `description` = 'כל הזמנות האתר גלויות' WHERE `optid` = 91;
UPDATE `system_options` SET `description` = 'כל האתרים גלויים' WHERE `optid` = 92;
UPDATE `system_options` SET `description` = 'הצג את כל מוצרי האתר' WHERE `optid` = 93;
UPDATE `system_options` SET `description` = 'שאלון' WHERE `optid` = 94;
UPDATE `system_options` SET `description` = 'שאלות' WHERE `optid` = 95;
UPDATE `system_options` SET `description` = 'רשימת שאלות' WHERE `optid` = 96;
UPDATE `system_options` SET `description` = 'הוסף שאלה' WHERE `optid` = 97;
UPDATE `system_options` SET `description` = 'הצג שאלה' WHERE `optid` = 98;
UPDATE `system_options` SET `description` = 'ערוך שאלה' WHERE `optid` = 99;
UPDATE `system_options` SET `description` = 'מחק שאלה' WHERE `optid` = 100;
UPDATE `system_options` SET `description` = 'אקדמי' WHERE `optid` = 101;
UPDATE `system_options` SET `description` = 'מוסדות' WHERE `optid` = 102;
UPDATE `system_options` SET `description` = 'רשימת מוסדות' WHERE `optid` = 103;
UPDATE `system_options` SET `description` = 'הוסף מוסד' WHERE `optid` = 104;
UPDATE `system_options` SET `description` = 'ערוך מוסד' WHERE `optid` = 105;
UPDATE `system_options` SET `description` = 'מחק מוסד' WHERE `optid` = 106;
UPDATE `system_options` SET `description` = 'תעריפי הנחה' WHERE `optid` = 107;
UPDATE `system_options` SET `description` = 'רשימת הנחות' WHERE `optid` = 108;
UPDATE `system_options` SET `description` = 'הוסף הנחה' WHERE `optid` = 109;
UPDATE `system_options` SET `description` = 'ערוך הנחה' WHERE `optid` = 110;
UPDATE `system_options` SET `description` = 'מחק הנחה' WHERE `optid` = 111;
UPDATE `system_options` SET `description` = 'נהל תלמידים' WHERE `optid` = 112;
UPDATE `system_options` SET `description` = 'רשימת תלמידים' WHERE `optid` = 113;
UPDATE `system_options` SET `description` = 'הוסף תלמיד' WHERE `optid` = 114;
UPDATE `system_options` SET `description` = 'ערוך תלמיד' WHERE `optid` = 115;
UPDATE `system_options` SET `description` = 'שנה סטטוס תלמיד' WHERE `optid` = 116;
UPDATE `system_options` SET `description` = 'מחק תלמיד' WHERE `optid` = 117;
UPDATE `system_options` SET `description` = 'חוגים' WHERE `optid` = 118;
UPDATE `system_options` SET `description` = 'רשימת חוגים' WHERE `optid` = 119;
UPDATE `system_options` SET `description` = 'הוסף חוג' WHERE `optid` = 120;
UPDATE `system_options` SET `description` = 'ערוך חוג' WHERE `optid` = 121;
UPDATE `system_options` SET `description` = 'מחק חוג' WHERE `optid` = 122;
UPDATE `system_options` SET `description` = 'חוגים למוסד' WHERE `optid` = 123;
UPDATE `system_options` SET `description` = 'רשימת נושאי מוסד' WHERE `optid` = 124;
UPDATE `system_options` SET `description` = 'הקצה נושא למוסד' WHERE `optid` = 125;
UPDATE `system_options` SET `description` = 'ערוך נושא של מוסד' WHERE `optid` = 126;
UPDATE `system_options` SET `description` = 'מחק נושא של מוסד' WHERE `optid` = 127;
UPDATE `system_options` SET `description` = 'נהל מדריכים' WHERE `optid` = 128;
UPDATE `system_options` SET `description` = 'רשימת מדריכים' WHERE `optid` = 129;
UPDATE `system_options` SET `description` = 'הוסף מדריך' WHERE `optid` = 130;
UPDATE `system_options` SET `description` = 'ערוך מדריך' WHERE `optid` = 131;
UPDATE `system_options` SET `description` = 'שנה סטטוס מדריך' WHERE `optid` = 132;
UPDATE `system_options` SET `description` = 'מחק מדריך' WHERE `optid` = 133;
UPDATE `system_options` SET `description` = 'מדריכים למוסדות' WHERE `optid` = 134;
UPDATE `system_options` SET `description` = 'רשימת מדריכי מוסד מוקצים' WHERE `optid` = 135;
UPDATE `system_options` SET `description` = 'הקצה מדריך למוסד' WHERE `optid` = 136;
UPDATE `system_options` SET `description` = 'ערוך מדריך מוסד מוקצה' WHERE `optid` = 137;
UPDATE `system_options` SET `description` = 'מחק מדריך מוקצה' WHERE `optid` = 138;
UPDATE `system_options` SET `description` = 'מדריכים לחוג' WHERE `optid` = 139;
UPDATE `system_options` SET `description` = 'רשימת מדריכי חוג מוקצים' WHERE `optid` = 140;
UPDATE `system_options` SET `description` = 'הקצה מדריך לחוג' WHERE `optid` = 141;
UPDATE `system_options` SET `description` = 'ערוך מדריך חוג' WHERE `optid` = 142;
UPDATE `system_options` SET `description` = 'מחק מדריך חוג' WHERE `optid` = 143;
UPDATE `system_options` SET `description` = 'צור דף שאלות' WHERE `optid` = 144;
UPDATE `system_options` SET `description` = 'רשימת דפים' WHERE `optid` = 145;
UPDATE `system_options` SET `description` = 'צור דף' WHERE `optid` = 146;
UPDATE `system_options` SET `description` = 'הצג דף' WHERE `optid` = 147;
UPDATE `system_options` SET `description` = 'מחק דף' WHERE `optid` = 148;
UPDATE `system_options` SET `description` = 'ערוך דף' WHERE `optid` = 149;
UPDATE `system_options` SET `description` = 'רק דפים משלי' WHERE `optid` = 150;
UPDATE `system_options` SET `description` = 'כל הדפים' WHERE `optid` = 151;
UPDATE `system_options` SET `description` = 'הצג שאלות בדף' WHERE `optid` = 152;
UPDATE `system_options` SET `description` = 'הורד דף בחינה' WHERE `optid` = 153;
UPDATE `system_options` SET `description` = 'הורד מפתח בחינה' WHERE `optid` = 154;
UPDATE `system_options` SET `description` = 'שנה סטטוס דף' WHERE `optid` = 155;
UPDATE `system_options` SET `description` = 'דוחות' WHERE `optid` = 156;
UPDATE `system_options` SET `description` = 'דוח תלמיד' WHERE `optid` = 157;
